# @package _group_
seed: 1
setup: metaworld
base_path:
log_dir: ${setup.base_path}/logs
save_dir: ${setup.log_dir}/experiment_test
device: cuda:0
id: sample
description: Sample Task
tags:
  # - sac
  # - metaworld
  # - baseline
  # - single_task
git:
  commit_id:
  has_uncommitted_changes:
  issue_id:
date:
slurm_id:
debug:
  should_enable: False
metadata_path: ${project_root}/metadata/task_embedding/roberta_small/metaworld-all.json
